@startuml
skinparam shadowing false

actor User

User -> "Client GUI": Withdraw money
activate "Client GUI"

"Client GUI" -> ATM: Withdraw money
activate ATM

ATM -> "Bank Server": Check balance
activate "Bank Server"

"Bank Server" -> Database: Get balance
activate Database

"Bank Server" <-- Database: balance
deactivate Database

"Bank Server" -> "Bank Server": Validate balance
activate "Bank Server"

alt valid balance

  "Bank Server" -> Database: Change balance
  activate Database

  "Bank Server" <-- Database: new balance
  deactivate Database

  ATM <-- "Bank Server": Accept withdrawl

  "Client GUI" <-- ATM: Accept withdrawl

  User <-- "Client GUI": Money

else invalid balance

  ATM <-- "Bank Server": Reject withdrawl
  deactivate "Bank Server"

  "Client GUI" <-- ATM: Reject withdrawl
  deactivate ATM

  User <-- "Client GUI": Rejection
  deactivate "Client GUI"

end

@enduml
