// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TA3.Data_Providers;

#nullable disable

namespace TA3.Migrations
{
    [DbContext(typeof(EfDataProvider))]
    partial class EfDataProviderModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TA3.Models.ProductEf", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("aisle")
                        .HasColumnType("text");

                    b.Property<decimal>("price")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("name");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
